### ISSUE TITLE
Bluetooth SPP 객체를 다른 액티비티로 넘겨주기

### ISSUE THREAD

**Issue by woomurf** [woomurf/2018-OpenSource-Project-Robo-Hand#3]
Bluetooth SPP 객체를 다른 액티비티로 넘겨주어 화면이 바뀌어도 bluetooth 연결이 유지되게 하기
- 다른 방법을 사용해도 좋음.

**Comment by as1084089** [comment]
담당 : 우현웅

**Comment by woomurf** [comment]
1. Serialize 방법 실패.
2. BluetoothSPP 객체를 service에 넣어서 구현해보려고 함.

**Comment by woomurf** [comment]
mac address를 다른 화면으로 넘어갈 때, 같이 넘겨주고 넘어간 화면에서 재 연결하는 것으로 해결
넘어갈 때, 연결을 끊고 넘어가서 다시 연결해야하는데 이 때 약간의 딜레이를 줘야함
